name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: /server
    environment:
      - AGENCIES_AMOUNT=1
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini


  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/agency.csv
    environment:
      - CLI_ID=1
    networks:
      - testing_net
    depends_on:
      - server


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
